### ISSUE TITLE
SQL logic error and other errors when iserting data (32 bits)

### ISSUE THREAD

**Issue by abdelouahabb** [Mr7F/sql-crypt#2]
I got lot of error from my web app (using Tornado, converted to an x86 EXE using Nuitka), the problem occurs when I try to insert some data,

I try using another DB clone that is not encrypted using 

```
# conn = Connection("./database/stocks.db", my_password)
conn = Connection("./database/stocks.db")
```

And here is the errors I get :

```
Traceback (most recent call last):
  File "C:\Users\ok\Desktop\cashier\app.py", line 99, in post
  File "D:\Build\apsw\apsw-3.38.5-r1\src\cursor.c", line 228, in resetcursor
apsw.SQLError: SQLError: SQL logic error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ok\Desktop\cashier\tornado\web.py", line 1713, in _execute
  File "C:\Users\ok\Desktop\cashier\app.py", line 96, in post
apsw.IOError: IOError: disk I/O error
```

`apsw.SQLError: SQLError: SQL logic error`

```
Traceback (most recent call last):
  File "D:\Build\apsw\apsw-3.38.5-r1\src\vfs.c", line 2091, in apswvfsfile_xWrite
  File "D:\Build\apsw\apsw-3.38.5-r1\src\pyutil.c", line 59, in Call_PythonMethod
  File "C:\Users\ok\Desktop\cashier\sqlcrypt.py", line 125, in xWrite
  File "C:\Users\ok\Desktop\cashier\sqlcrypt.py", line 125, in xWrite
  File "C:\Users\ok\Desktop\cashier\sqlcrypt.py", line 125, in xWrite
  [Previous line repeated 70 more times]
  File "C:\Users\ok\Desktop\cashier\sqlcrypt.py", line 142, in xWrite
TypeError: 'bytes' object does not support item assignment

During handling of the above exception, another exception occurred:

SystemError: D:\a\1\s\Python\traceback.c:44: bad argument to internal function

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ok\Desktop\cashier\asyncio\windows_events.py", line 316, in run_forever
  File "C:\Users\ok\Desktop\cashier\asyncio\base_events.py", line 570, in run_forever
  File "C:\Users\ok\Desktop\cashier\asyncio\base_events.py", line 1859, in _run_once
  File "C:\Users\ok\Desktop\cashier\asyncio\events.py", line 81, in _run
SystemError: D:\a\1\s\Python\traceback.c:44: bad argument to internal function

During handling of the above exception, another exception occurred:

SystemError: D:\a\1\s\Python\traceback.c:44: bad argument to internal function

During handling of the above exception, another exception occurred:

SystemError: D:\a\1\s\Python\traceback.c:44: bad argument to internal function

```

**Comment by Mr7F** [comment]
Hello

> converted to an x86 EXE using Nuitka

Can you reproduce the issue with a simple python script ? If no it's not the purpose of the lib to support Nuitka sorry (and it might come from APSW)

**Comment by Mr7F** [comment]
By looking at your error, `D:\Build\apsw\apsw-3.38.5-r1\src\cursor.c` I see it come from APSW indeed, so there's nothing I can do, it's not under my control sorry

**Comment by abdelouahabb** [comment]
> By looking at your error, `D:\Build\apsw\apsw-3.38.5-r1\src\cursor.c` I see it come from APSW indeed, so there's nothing I can do, it's not under my control sorry

Thank you, after investigating, seems it can't handle long transactions when encrypted, It worked without encrypting, so I split the transaction to small ones and it works,
Thank you again ^^
